export type genres =
  | "Fantasy"
  | "Science Fiction"
  | "Romance"
  | "Horror"
  | "Mystery"
  | "Thriller"
  | "Historical"
  | "Adventure"
  | "Drama"
  | "Comedy"
  | "Action"
  | "Dystopian"
  | "Supernatural"
  | "Paranormal"
  | "Slice of Life"
  | "Crime"
  | "Western"
  | "Biography"
  | "Autobiography"
  | "Non-fiction"
  | "Young Adult"
  | "Children"
  | "Light Novel"
  | "Classic"
  | "Poetry"
  | "Philosophy";
